language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: “falessiinguniroma2it-github"
    token:
      secure: “travis encrypt dfdf31fd8d77fbb5257a379189abd6a011c0f411”
script:
- ant build
- sonar-scanner